### ISSUE TITLE
[Bug] crash ZXingAutofocusScannerView.java: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by luckv** [mono0926/barcode_scan2#33]
**Describe the bug**
Only one time, the release version in the play store of the app has crashed. 

**To Reproduce**
Can't reproduce. The error comes from crashlytics

**Logs**
Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1910)
       at de.mintware.barcode_scan.ZXingAutofocusScannerView.setupCameraPreview(ZXingAutofocusScannerView.java)
       at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Environment:**
 - [ ] iOS: No
 - [x] Android: 7.1.2
 - [x] Real device: Samsung Galaxy S8+
 - [ ] Emulator: No
 - Version of `barcode_scan`: 4.1.4
 - Output of `flutter --version`:
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by utsavDave97** [comment]
Getting the same. Any solution for this one?

**Comment by DavideBicego** [comment]
Same issue here, had 29 crashes in production in the last 90 days.
Here's a log:
```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:2091)
       at de.mintware.barcode_scan.ZXingAutofocusScannerView.setupCameraPreview(ZXingAutofocusScannerView.java:6)
       at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:18)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Comment by surajpunemaha** [comment]
Having same issue. Any updates??

**Comment by surajpunemaha** [comment]
> Same issue here, had 29 crashes in production in the last 90 days. Here's a log:
> 
> ```
> Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
>        at android.hardware.Camera.native_getParameters(Camera.java)
>        at android.hardware.Camera.getParameters(Camera.java:2091)
>        at de.mintware.barcode_scan.ZXingAutofocusScannerView.setupCameraPreview(ZXingAutofocusScannerView.java:6)
>        at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:18)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:226)
>        at android.os.Looper.loop(Looper.java:313)
>        at android.app.ActivityThread.main(ActivityThread.java:8641)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
> ```

Found any solution??

**Comment by kluverua** [comment]
I have reproduced it on the emulator "Nexus 9" with fresh system image: Android 11.0 (Google APIs) x86 armeabi-v7a

**Comment by paraslaxkar** [comment]
Any solution for this issue ???

**Comment by surajpunemaha** [comment]
> Any solution for this issue ???

Don't know what was the reason for this issue. I have Updated flutter and all dependencies to latest one. Now issue is gone.

**Comment by paraslaxkar** [comment]
after updating dependencies still getting this issue , any solution?
