### ISSUE TITLE
[Release App Crashed ]

### ISSUE THREAD

**Issue by mohitjadav86** [mono0926/barcode_scan2#45]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.u' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in /data/app/~~Ic1pW95wWnDuOe5V4CR2FQ==/com.addpix.inventrocloud-OCVG4ZkOa_H7IFOZlGLdkw==/base.apk)
E/AndroidRuntime(25204): 	at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(Unknown Source:7)
E/AndroidRuntime(25204): 	at android.view.View.dispatchAttachedToWindow(View.java:22010)
E/AndroidRuntime(25204): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
E/AndroidRuntime(25204): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
E/AndroidRuntime(25204): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
E/AndroidRuntime(25204): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
E/AndroidRuntime(25204): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
E/AndroidRuntime(25204): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3135)
E/AndroidRuntime(25204): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
E/AndroidRuntime(25204): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
E/AndroidRuntime(25204): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
E/AndroidRuntime(25204): 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
E/AndroidRuntime(25204): 	at android.view.Choreographer.doFrame(Choreographer.java:744)
E/AndroidRuntime(25204): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
E/AndroidRuntime(25204): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(25204): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25204): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(25204): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(25204): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25204): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(25204): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by vinodlee** [comment]
me also same problem. any solution is there?

**Comment by mohitjadav86** [comment]
> me also same problem. any solution is there?

Able to solve this issue by upgrading Gradle.
Will try to give PR ASAP

**Comment by yavanya** [comment]
https://github.com/mono0926/barcode_scan2/issues/36#issuecomment-1023601522

**Comment by yavanya** [comment]
> me also same problem. any solution is there?

https://github.com/mono0926/barcode_scan2/issues/36#issuecomment-1023601522
